[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = [
  'npx vite build',
  'npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --target=node18'
]

[start]
cmd = 'cd dist && node index.js'